### ISSUE TITLE
Website for AndrOBD

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#103]
It would be nice to have an AndrOBD website so any articles in the future can link to it and the website would make a better visual representation of the project that could attract developers/contributors better.

A completely free and simple option is via Github Pages, that a lot of github open source projects are using, and you can even use/buy a custom domain like "www.androbd.org" if you want: https://pages.github.com/

> Hosted directly from your GitHub repository. Just edit, push, and your changes are live.
> No databases are needed to be set up and no servers to configure

Examples of repos that use github pages: https://github.com/collections/github-pages-examples

Interesting article: https://www.toptal.com/github/unlimited-scale-web-hosting-github-pages-cloudflare

> Consider [Jekyll](https://jekyllrb.com/). You give it [Liquid ](https://jekyllrb.com/docs/liquid/)templates and Markdown content
Free Jekyll templates: https://jekyllthemes.io/free

**Comment by sampoder** [comment]
I'd love to work on this!

**Comment by sampoder** [comment]
By the way @aha999 feel free to give feedback on the PR!

**Comment by sampoder** [comment]
With #106 being merged, I think this issue should be closed!

**Comment by fr3ts0n** [comment]
Thanks to @sampoder for providing Landing page in PR #106 .
Page is now available on http://fr3ts0n.github.io/AndrOBD/
