### ISSUE TITLE
Speed & RPM dashboard

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#112]
Request for a Speed & RPM dashboard.
- Gifs below recorded from this website: http://metinseylan.com/
- Source of that dashboard linked to: https://github.com/MetinSeylan/Kaput
- Related to issue #104 

It could look like this:
![f1y5q996FW](https://user-images.githubusercontent.com/50620416/74491619-74e9dd80-4ecc-11ea-9f8d-1f8c9d8a5e56.gif)

![F2PM8mR8an](https://user-images.githubusercontent.com/50620416/74491624-76b3a100-4ecc-11ea-9035-1bdf86b1dbd5.gif)

**Comment by aha999** [comment]
check this speedometer opensource project out. it would be awesome if you could integrate it into AndrOBD.

>  Dynamic Speedometer and Gauge for Android. amazing, powerful, and multi shape ⚡ 

https://github.com/anastr/SpeedView

**Comment by fr3ts0n** [comment]
This could be quite a good alternative to the rudimentary gauges in achartengine library.
I will take a look at this.
I was hoping to find a complete replacement for the achartengine (i.e. chartfx/tilefx) but I don't want to complicate the project by adding JavaFX semantics.

**Comment by fr3ts0n** [comment]
Here is a sample dash using SpeedView:
![Screenshot_20200731-131018](https://user-images.githubusercontent.com/2822578/89030370-9df21380-d330-11ea-88b1-c3c36b5954ab.png)

Does that look reasonable?

The only downside:
- App size is about doubled, since I need to add Kotlin support

**Comment by fr3ts0n** [comment]
Test version (V2.2.0) is here:
https://t.me/c/1434285001/156

![Screenshot_1596214630](https://user-images.githubusercontent.com/2822578/89061396-ef1bfa80-d364-11ea-8c82-4106a1d92c0f.png)

**Comment by anastr** [comment]
Hi @fr3ts0n 
You can use version `1.3.0`, the last version written in Java, a lot of [changes](https://github.com/anastr/SpeedView/releases) since.

You may need to add some `sv_cutPadding` to see first and last tick.

Good work!.

**Comment by fr3ts0n** [comment]
Hi @anastr 

Thanks for the hint with ```sv_cutPadding``` :+1:  

![Screenshot_1596282217](https://user-images.githubusercontent.com/2822578/89101072-158d7480-d3fd-11ea-9dc7-3e959907b9d4.png)

In the last java-based V1.3.0 the AwesomeSpeedometer has quite some tick scaling issues, so I'd rather have the kotlin support.

**Comment by aha999** [comment]
@anastr for updates/chat about this project, please join a [telegram group](https://t.me/joinchat/G60ltQv5CCEQ94BZ5yWQbg)
