### ISSUE TITLE
Tested the app on Hyundai i10 Model - Shows everything zero after connection

### ISSUE THREAD

**Issue by pratt1305** [fr3ts0n/AndrOBD#114]
i tested this app with my car hyndai i10 india the devices gets connected but then it shows nothing on any of the chart. where am i going wrong ?

![Screenshot_20200212-211350](https://user-images.githubusercontent.com/8825570/74900166-f2c65100-53c4-11ea-8952-0ea8a4b633ed.png)
![Screenshot_20200212-211355](https://user-images.githubusercontent.com/8825570/74900171-f3f77e00-53c4-11ea-95c5-91c8137e90a1.png)
![Screenshot_20200212-211359](https://user-images.githubusercontent.com/8825570/74900173-f4901480-53c4-11ea-985a-125f18aeead7.png)
![Screenshot_20200212-211403](https://user-images.githubusercontent.com/8825570/74900175-f528ab00-53c4-11ea-92a3-c5ae2272e69e.png)
![Screenshot_20200212-211637](https://user-images.githubusercontent.com/8825570/74900176-f5c14180-53c4-11ea-949f-731d043bf818.png)

**Comment by pratt1305** [comment]
Are there any sepecific guidelines that i have missed ?

**Comment by fr3ts0n** [comment]
Hi @pratt1305 
I've never seen that one before ...
Please could you attach some log files as mentioned in https://github.com/fr3ts0n/AndrOBD/wiki/Reporting-improvements---issues
Thx

**Comment by pratt1305** [comment]
Log Files  As mentioned

[AndrOBD.log.3.txt](https://github.com/fr3ts0n/AndrOBD/files/4234282/AndrOBD.log.3.txt)
[AndrOBD.log.4.txt](https://github.com/fr3ts0n/AndrOBD/files/4234283/AndrOBD.log.4.txt)
[AndrOBD.log.1.txt](https://github.com/fr3ts0n/AndrOBD/files/4234284/AndrOBD.log.1.txt)
[AndrOBD.log.2.txt](https://github.com/fr3ts0n/AndrOBD/files/4234285/AndrOBD.log.2.txt)

**Comment by fr3ts0n** [comment]
Thank you, you found a good one ...
I don't know what I have tested for the last release, but it was definitely not the latest build ... 

Fixed with latest commit

Test version V2.1.3 is available on [AndrOBD_DEV channel](https://t.me/AndrOBD_dev)

**Comment by pratt1305** [comment]
Thanks @fr3ts0n  Issue has been solved now device is working fine i tested on 2 cars
