### ISSUE TITLE
Transmission Fluid Temperature?

### ISSUE THREAD

**Issue by mikegilchrist** [fr3ts0n/AndrOBD#119]
I've got a 2013 Toyota Sienna and am trying to check my ATF temperature per the instructions for correctly filling the transmission fluid which is supposed to be in the 100-130F range.  I can't seem to find any reading corresponding to the fluid.  What am I missing?

**Comment by fr3ts0n** [comment]
Most likely ATF temperature is not supported by the OBD implementation of your car.

**Comment by mikegilchrist** [comment]
Hmmm, but I see other non-open source apps offering this info, usually with a toyota specific plug in.

**Comment by mikegilchrist** [comment]
Any idea what the CAT temperature readings are? There are 4 of them.

**Comment by fr3ts0n** [comment]
Catalytic converter temperature.
If your car has a 2-Bank system 4 readings domake sense ...
Bank 1/2, Pre-/Post Converter

**Comment by mikegilchrist** [comment]
Ahh.  That makes more sense.  

Before I close this issue, I wanted to mentionI found a way to monitor the temperature by jumping the OBD pins. I describe it [here](https://www.siennachat.com/threads/transmission-fluid-change-drain-when-oil-cold-or-warm-and-engine-running-or-stopped.63868/post-352833) (in case any one is interested)

**Comment by fr3ts0n** [comment]
Thanks for sharing this information
