### ISSUE TITLE
Demo mode [feature request]

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#125]
Enable option/button to turn on demo mode, if not connected to the adapter, which would generate random data, so the users can see/test the app in full potential, without needing to be connected to the obd adapter.

**Comment by fr3ts0n** [comment]
This is the case if you start the app without allowing connection to Bluetooth device.
* Demo mode is indicated in app ...
* and documented here: https://github.com/fr3ts0n/AndrOBD/wiki/OBD-connection#demo-mode
