### ISSUE TITLE
Data charts Dashboard HUD

### ISSUE THREAD

**Issue by jairdomingues** [fr3ts0n/AndrOBD#127]
Data charts
Dashboard
Head up display
are not available in demo mode.

**Comment by fr3ts0n** [comment]
All these functions are available in demo mode as well ...

[AndrOBD-selection.zip](https://github.com/fr3ts0n/AndrOBD/files/5169281/AndrOBD-selection.zip)

**Comment by fr3ts0n** [comment]
Added description how to activate **DEMO mode** to wiki
- https://github.com/fr3ts0n/AndrOBD/wiki/OBD-connection
- https://github.com/fr3ts0n/AndrOBD/wiki/Frequently-asked-questions
