### ISSUE TITLE
 white screen on app launch

### ISSUE THREAD

**Issue by 532910** [fr3ts0n/AndrOBD#133]
White flash burns eyes:
![ScreenRecord-2020-12-12-02-43-38](https://user-images.githubusercontent.com/14617699/101964905-fb259c00-3c23-11eb-9782-ca1d4d2413f9.gif)
For example other apps like Orgzly, Binary Eye or Car Report has no flash.
v2.2.2, android 10

**Comment by fr3ts0n** [comment]
Thanks for your report.

This will be fixed in next release.

**Comment by fr3ts0n** [comment]
Fixed test version V2.2.3 is available here: https://t.me/AndrOBD_dev/229
