### ISSUE TITLE
protocol error infinite loop

### ISSUE THREAD

**Issue by kavol** [fr3ts0n/AndrOBD#14]
Trying to use AndrOBD with my car (see issue #10), version 1.3.9 crashes.
It displays an error, see the screenshot, many times and then it closes, presumably exhausting resources.

![screenshot_2016-01-06-19-04-47](https://cloud.githubusercontent.com/assets/2169753/12168202/0d447bc4-b531-11e5-9c27-bffab05ec1f6.png)

**Comment by kavol** [comment]
logs here: http://uloz.to/x78n1mJN/androbd-16-01-06-zip
(this tracker still doesn't accept zip despite it says it does ...)

**Comment by fr3ts0n** [comment]
Thanks for the report.

Yep. this was a loop condition, since the service request was not aborted with the NRC.
The loop was triggered with the ELM prompt which wasn't part of my ELM simulation for testing ...

fixed with V1.3.11
