### ISSUE TITLE
Open web links inside the app

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#141]
**Is your feature request related to a problem? Please describe.**
Currently, when for example you hold the diagnostic trouble code, AndrOBD opens a search link by externally opening a default web browser app to display the search for that error code in a new tab, which is personally very annoying, as doing so means we have to close the tab manually and then close the browser and then go back to AndrOBD via app manager switch.

**Describe the solution you'd like**
Open internet links inside the app by accessing the default browser that opens as a pop-up embedded browser. That way, we will be able to see what the error code was, and press X to close that search and go straight back to andrOBD, or what you were viewing. This should be a default behaviour as it would be much more user friendly and convenient, but there should also be a toggle in the settings "Open web links in-app" that would be switched ON by default.

**Additional context**
Apps like Reddit, Discord etc. do this.
Toggle:
![slika](https://user-images.githubusercontent.com/50620416/114779102-f6a9f500-9d75-11eb-99f4-5e814b92c54f.png)

Opened (cropped) website inside the app with pop-up (menu is at the bottom probably because i have it set like this in Firefox), it also has options at the right side like Copy, share, open in main browser...
![slika](https://user-images.githubusercontent.com/50620416/114780453-b77ca380-9d77-11eb-9e3b-887af1204a08.png)

Clicking options:
![slika](https://user-images.githubusercontent.com/50620416/114786896-2d383d80-9d7f-11eb-96c7-28fd41335cbf.png)

**Comment by fr3ts0n** [comment]
Do you mean something like this?
That is what AndrOBD already does ...

![androbd_dfc_lookup](https://user-images.githubusercontent.com/2822578/114914173-4b0aae80-9e22-11eb-94f5-ea8e0cfb06d4.gif)

**Comment by aha999** [comment]
No. It should open a default browser's tab.
Just found out how it is called: **Browser Custom tabs** (or Chrome custom tabs).

- [Chrome Custom Tabs](https://youtu.be/QOxIdbNwpx0), [Overview](https://developer.chrome.com/docs/android/custom-tabs/overview/)
- [Best Practices for Custom Tabs](https://medium.com/google-developers/best-practices-for-custom-tabs-5700e55143ee)
- i think this may be a dev site for java browser custom tabs: [androidx.browser.customtabs](https://developer.android.com/reference/androidx/browser/customtabs/package-summary)

**Comment by aha999** [comment]
No. You have WebView and it has limited abilities, and isn't as convenient. It should open a default browser's custom tab.

It is called **Browser Custom tabs** (or Chrome custom tabs).

- [Chrome Custom Tabs](https://youtu.be/QOxIdbNwpx0), [Overview](https://developer.chrome.com/docs/android/custom-tabs/overview/)
- [Best Practices for Custom Tabs](https://medium.com/google-developers/best-practices-for-custom-tabs-5700e55143ee)
- i think this may be a dev site for java browser custom tabs: [androidx.browser.customtabs](https://developer.android.com/reference/androidx/browser/customtabs/package-summary)

**Comment by fr3ts0n** [comment]
This only uses webview if NO other browser is installed, which is the case on the emulator instance above.
If installed it uses your default browser.

**Comment by fr3ts0n** [comment]
I don't really like the idea of implementing something like this, because it breaks at least one of below golden rules
- Functional
- Lean
- Backwards compatible

It would break compatibility with older versions of Android.
I prefer to keep AndrOBD backwards compatible to allow users with older devices also to benefit from functional updates.

**Comment by aha999** [comment]
In that case, there should at least be a toggle option to enable Browser Custom Tabs (open web links in-app). 

That way, we wouldn't have to close the tabs and browser / switch applications, because Browser custom tabs have a close button that returns you to the application, i think that is way more convenient and elegant way after viewing the diagnostic code online, and it uses a default browser, all major browsers support browser custom tabs.

**Comment by fr3ts0n** [comment]
I don't get the sense of this ...
- The solution would be only available for latest version 
  - NOT COMPATIBLE 
    - -> keep 2 solutions optional 
      - NOT LEAN
      - Support more complex due to functional variants

It may look look more sexy to you to have in-app browse window, but I can not see any functional advantage to the current state.
- Single solution 
  - default browser is opened
  - close browser returns to app (last state)
  - works on ALL versions of Android
    - identical behaviour between different versions
