### ISSUE TITLE
Long press to copy VIN

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#155]
**Is your feature request related to a problem? Please describe.**
If we want to search info by VIN online, we have to rewrite it from the interface.

**Describe the solution you'd like**
Make long pressing the VIN, copy it. And the text below showing "VIN copied to clipboard".

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by fr3ts0n** [comment]
I would not limit that to the VIN.
This could be done with any VID item

**Comment by fr3ts0n** [comment]
Test version: V2.3.2
https://t.me/AndrOBD_dev/234
