### ISSUE TITLE
Some strings are not in Weblate. Please update/synchronize them.

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#156]
**Describe the bug**
Strings like "Identify plugins", "OBD test control","Evaporative tsystem leak test", "Diesel Particulate filter regeneration" and others are not in Weblate to translate.

**Describe solution**
Update the strings so all of them will be translatable in Weblate.

**Important details on your environment:**
- Android OS version 11
- AndrOBD version 2.3.1 (Test version)
- OBD adapter type Demo

**Comment by fr3ts0n** [comment]
OBD test control and the new OBD test description are translatable on weblate.
These strings are located in the platform independent OBD library and therefore translated in the OBD data section

There are several strings from **plugin** module which are currently not mirrored to weblate for translation

**Comment by fr3ts0n** [comment]
Now also AndrOBD plugin framework strings are translatable in weblate
