### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by stef204** [fr3ts0n/AndrOBD#164]
Using latest version.
How does one access the Dashboard?
I don't see it anywhere.  Is it dependent on type of ECU? Needs compatibility?
I am able to connect and read codes, it detects my VIN, etc.

**Comment by fr3ts0n** [comment]
- Select "OBD Data"
- Select your desired data items
  - After selection of >0 Data items you get a function bar at the top
    - Select desired function: 
      - Dashboard 
      - HUD
      - Graph
      - Filtered list

**Comment by stef204** [comment]
I see it now, thanks.
