### ISSUE TITLE
Separate repositories for each plugin

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#171]
**Is your feature request related to a problem? Please describe.**
Currently, plugins in F-Droid have all the same name/information/icons, so it's very confusing what you're looking at. Also, the plugins seem to be in one repository.

![image](https://user-images.githubusercontent.com/50620416/130317159-4aac658b-28d0-41b6-a567-58106c62ed1c.png)

**Describe the solution you'd like**
I think it would be better if each plugin would have its own repo. All the repos would be listed/linked in the main AndrOBD project page, so they would be easily findable as a project, and could be developed separately. 
I think that separating them would be better for development of each plugin and cause less confusion and better displaying of information on F-Droid, like different icons, descriptions... And if users wanted to fork/improve a specific plugin, they'd have it all in one repo of the plugin they wish to improve.

**Additional context**
I'm not the expert in this area and don't have much experince on this or with developing strategy so i may be wrong, but it just seems like separate repos could solve many things from my perspective.

**Comment by fr3ts0n** [comment]
This is already fixed in F-droid:
![image](https://user-images.githubusercontent.com/2822578/132995220-f379960d-fe07-41a7-b6c3-c16b464f9136.png)
