### ISSUE TITLE
Send data to a server

### ISSUE THREAD

**Issue by lucamarchiori** [fr3ts0n/AndrOBD#176]
It would be very useful to add a feature that allows you to send data every few seconds to a server via a simple http request.

**Comment by fr3ts0n** [comment]
As @hufman already stated on telegram channel: Did you take a look at the [MQTT plugin](https://search.f-droid.org/?q=androbd&lang=de)? These plugins are currently available... 
For additional plugins you are welcome to help creating a new one ...
