### ISSUE TITLE
Add P0000 in $03 if no error code is stored 

### ISSUE THREAD

**Issue by Artur-debug** [fr3ts0n/AndrOBD#178]
Please add P0000 if no error code is stored in a next Update. So I can immediately see that there is communication and that ELM has received an answer from the ECU. 

<img src="https://user-images.githubusercontent.com/84518891/134817575-24fb9ee6-6fbe-4c10-8194-4ea55304a5c0.jpg" width="300"/>

**Comment by fr3ts0n** [comment]
Mode $3 should already display a "No codes set" entry if there is no code responded by the vehicle.
Could you please attach a log file of this action?
I would like to verify why your device doesn't show this message.
Thx

**Comment by Artur-debug** [comment]
![screen-2021-09-26-20-15-55](https://user-images.githubusercontent.com/84518891/134819451-7a7380d6-daab-479f-991d-c75ddc22d68b.png)

[AndrOBD.log.0.0900fix.txt](https://github.com/fr3ts0n/AndrOBD/files/7231980/AndrOBD.log.0.0900fix.txt)
