### ISSUE TITLE
Give the possibility to change plot color 

### ISSUE THREAD

**Issue by Artur-debug** [fr3ts0n/AndrOBD#179]
Please enlarge the graphics axis lettering and give the option to choose other colors. It is very difficult to see something. 

<img src="https://user-images.githubusercontent.com/84518891/134818745-ae1f98c0-8885-4d7e-aa3c-ed1b3924418e.jpg" width="300"/>

**Comment by fr3ts0n** [comment]
Data display customization introdued with V2.5.0
Test version available: https://t.me/AndrOBD_dev

**Comment by fr3ts0n** [comment]
Released with [V2.5.2](https://github.com/fr3ts0n/AndrOBD/releases/tag/V2.5.2).
will be available on F-Droid soon ...
