### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.3.12.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [fr3ts0n/AndrOBD#18]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.3.12.

**Comment by fr3ts0n** [comment]
Already available. Pressing on the Version number within the APP leads you to the project releases page.

**Comment by locutis-of-borg-1999** [comment]
Oh, so it shouldn't be too strenuous, by the next release, to add that link in the F-Droid app's info' page, under "links".

It's good to see what's been fixed.  People uninstall app's, over issues, and look for changelogs, even prior to first install.

I suppose you could tell them, in the description, to "just install it", and look for the hidden link.

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by alanthehat** [comment]
I too would like to see a [changelog] link on F-Droid

**Comment by fr3ts0n** [comment]
added metadata change to app profile in f-droid repo and created a merge request
I hope this does the job ...
