### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#193]
In [configuration instructions](https://github.com/fr3ts0n/AndrOBD/wiki/Configuration) i saw a small grammar error. Add a letter "D" to the "AnrOBD".

Screenshot:
![image](https://user-images.githubusercontent.com/50620416/161538710-1f61f287-7fe3-43d8-8fdd-fa78ed9afcbd.png)

**Comment by fr3ts0n** [comment]
Corrected.
Thank you for spotting 👍
