### ISSUE TITLE
Enhanced diagnostics (ABS, Airbag, Climate Control...)

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#201]
**Is your feature request related to a problem? Please describe.**
Currently there is no enhanced diagnostic for vehicles, like ABS, Airbag, Climate Control, etc. Some diagnostic apps offer this possibility but it is an expensive one, some apps offer it for free if their specific adapter brand is purchased.

**Describe the solution you'd like**
If my understanding of this topic is correct, and this enhanced diagnostic feature depends on the app, a database for enhanced diagnostic codes could be created, where anyone could contribute to, so it would offer manufacturer-specific codes for all things described above or more.

**Additional context**
I am not sure if this depends on paid licenses from car manufacturers, but optional addons for enhanced diagnostics would be nice, if it is even possible to open source it legally.

**Comment by fr3ts0n** [comment]
Please see answer in [Wiki](https://github.com/fr3ts0n/AndrOBD/wiki/Frequently-asked-questions#will-androbd-support-additional-non-obd-sensor-data)
