### ISSUE TITLE
Add Translating section to Wiki

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#216]
**Is your feature request related to a problem? Please describe.**
There is currently no instructions section in the AndrOBD Wiki as to how to translate the app.

**Describe the solution you'd like**
Surely Weblate is not the only way of translating AndrOBD, and if it is not, instructions on translating should be made in the Wiki, on how to translate in the Weblate, and also if there are other methods of translating.

**Additional context**
If this issue gets the Translating section in the Wiki, i will update the readme and include the Translating link.

**Comment by fr3ts0n** [comment]
added here:
https://github.com/fr3ts0n/AndrOBD/wiki/Language-translation

**Comment by aha999** [comment]
That's awesome, so fast and well done. you amaze me...
