### ISSUE TITLE
Where can I print OBD raw data？？

### ISSUE THREAD

**Issue by 912334508** [fr3ts0n/AndrOBD#218]
# Describe the bug

## AndrOBD Debug log files

Please attach AndrOBD debug log files.

AndrOBD stores log files in a subdirectory on your primary storage device. (com.fr3ts0n.ecu.gui.androbd/log/AndrOBD.log.*)

### Log detail level

The detail level of the logged debug information can be adjusted in the Settings > Development options > Logging level.

By default the detail level is set to INFO.
Preferred detail level for issue analysis is DEBUG. (Since V1.5.0 this level is called FINE)

## Important details on your environment:

- Android OS version:
- AndrOBD version:
- OBD adapter type:
- Connected vehicle make, type, year, engine size:

**Comment by fr3ts0n** [comment]
Pls could you describe in detail what you ask for (in the headline only)?

- OBD RAW data
  - Do you mean an OBD protocol communication log?

- Print
  - Do you mean print to paper / display?

Thank you
