### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by openmotion** [fr3ts0n/AndrOBD#219]
# Compilation error

I execute this command : 

./gradlew build

 FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':androbd:mergeReleaseNativeLibs'.
> Could not resolve all task dependencies for configuration ':androbd:releaseRuntimeClasspath'.
   > Could not resolve project :plugin.
     Required by:
         project :androbd
      > No matching configuration of project :plugin was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.2.1', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by fr3ts0n** [comment]
https://github.com/fr3ts0n/AndrOBD/wiki/Frequently-asked-questions#build-problems---could-not-resolve-project-plugin
