### ISSUE TITLE
Issue solved. #Convert Intellij to android for AndrOBD

### ISSUE THREAD

**Issue by carpiko1010** [fr3ts0n/AndrOBD#22]
this andrOBD project is made on intellij, when i import it in android studio, it doesnt recognize the libraries jar files and throws this error.
Error:(21, 19) error: package javax.swing does not exist
Error:(26, 44) error: package javax.swing does not exist
Error:(80, 22) error: cannot find symbol class Icon
Error:(116, 21) error: package javax.swing does not exist
Error:(117, 21) error: package javax.swing does not exist

**Comment by carpiko1010** [comment]
I got help from your solution that you provided to exclude the jawa swing calsses.

**Comment by fr3ts0n** [comment]
Sorry for the late response. 
Please see answers on issues #1 and #16.
I will add this to the README for future wiithin rhe next days
