### ISSUE TITLE
flashing VINs

### ISSUE THREAD

**Issue by Geremia** [fr3ts0n/AndrOBD#223]
Could AndrOBD flash VINs, or is this something ELM327 dongles cannot do?

**Comment by fr3ts0n** [comment]
Unfortunately this is nothing you can do using OBD protocol. 
This is very OEM specific and usually requires some vehicle specific Secrets. (for obvious reasons)

**Comment by Geremia** [comment]
@fr3ts0n oh 🆗. thank you
