### ISSUE TITLE
shows connecting in OBD fault code permanent Bug report

### ISSUE THREAD

**Issue by monikamishra-54** [fr3ts0n/AndrOBD#225]
# Describe the bug

No data->Connecting in OBD fault code(permanent)

## AndrOBD Debug log files

I/com.fr3ts0n.prot: Status change: Connected->No data
I/com.fr3ts0n.prot: Status change: No data->Connecting
I/com.fr3ts0n.prot: Status change: Connecting->No data
I/com.fr3ts0n.prot: Status change: No data->Connecting
I/com.fr3ts0n.prot: Status change: Connecting->No data
I/com.fr3ts0n.prot: Status change: No data->Connecting
I/com.fr3ts0n.prot: Status change: Connecting->No data
I/com.fr3ts0n.prot: Status change: No data->Connecting
I/com.fr3ts0n.prot: Status change: Connecting->No data
I/com.fr3ts0n.prot: Status change: No data->Connecting

## Additional context
<img width="1405" alt="Screenshot 2022-12-29 at 4 32 45 PM" src="https://user-images.githubusercontent.com/58734760/209943506-7f7a7635-065c-4120-b904-e39284a8b33a.png">

**Comment by fr3ts0n** [comment]
Please attach log file (FINE)
See: https://github.com/fr3ts0n/AndrOBD/wiki/Reporting-improvements---issues#debug-log-files

In above logcat I can see the symptoms, but NOT the communication which lead to that ...
