### ISSUE TITLE
OBD Protocol Error

### ISSUE THREAD

**Issue by MudassarMinhasPZ** [fr3ts0n/AndrOBD#227]
After connecting with obd device and click on OBD data tab under services of action bar. its show error of obd protocol error. 

1. Connect with OBD Device
2. Click on Service menu from action bar
3. Click on OBD Data
4. it show obd protocol error but sometime its shows data don't know why its show data and why not.

- Android OS version: android 12
- AndrOBD version: Updated
- OBD adapter type: ELM 327
- Connected vehicle Proton 

![ff7c1a5d980e818029b07a03dd743629d474c398](https://user-images.githubusercontent.com/121489499/209944970-9c0b6809-9781-4fca-be94-bd59a4d861b8.jpeg)

**Comment by fr3ts0n** [comment]
No analysis possible without corresponding protocol logging data ...
