### ISSUE TITLE
Confirmed fault code

### ISSUE THREAD

**Issue by monikamishra-54** [fr3ts0n/AndrOBD#228]
**Is your feature request related to a problem? Please describe.**
Is app providing confirmed fault code

**Describe the solution you'd like**
confirmed and permanent fault code is same.

**Describe alternatives you've considered**
https://support.bluedriver.com/support/solutions/articles/43000551802-confirmed-pending-permanent-and-enhanced-codes#:~:text=Once%20the%20sensor%20starts%20to,a%20pending%20code%20will%20appear.&text=A%20confirmed%20code%20indicates%20that,an%20issue%20requiring%20your%20attention

This article shows three types of fault code

**Comment by fr3ts0n** [comment]
NO, permanent != confirmed
- Pending codes did occur at least once within the drive cycle, but not long-/often enough to be confirmed yet
- Confirmed codes did occur multiple times within the last drive cycles, but may be cleared by "Clear DFC" service.
  - If problem still occurs, DFC will be activated again
- Permanent codes may not be cleared by "Clear DFC" service. 
  - They may be resolved in a garage by parts change only.

**Comment by monikamishra-54** [comment]
Thank you for quick response,
Sorry for silly questions but I'm new in this field my question is app is providing all types of fault code i.e Powertrain, Chassis, Body
![image](https://user-images.githubusercontent.com/58734760/209986580-28e88429-412f-4940-b4a2-a388801e62de.png)

**Comment by fr3ts0n** [comment]
See current supported code list: https://github.com/fr3ts0n/AndrOBD/blob/master/library/src/main/java/com/fr3ts0n/ecu/prot/obd/res/codes.properties

However: Above list is the superset of known codes. You will only see the codes which the vehicle supports on OBD protocol.

**Comment by monikamishra-54** [comment]
Thank You, but this means app doesn't support Chassis and body code?

**Comment by fr3ts0n** [comment]
Yes, that is what OBD protocol is designed for: Emissions related diagnostics!

**Comment by monikamishra-54** [comment]
Thanks for response, Can you help me which library or any github open source code or any idea how we can achieve this for getting  Chassis and body code from OBD device. Is there way we can extent this code to get other DTC services.
"I tried everywhere but didn't find anything related this. Please Help "

**Comment by fr3ts0n** [comment]
For implememting NON OBD codes / data you need a lot of:
- OEM specific documentation
- Time / equipment for reverse engineering
See also: https://github.com/fr3ts0n/AndrOBD/wiki/Frequently-asked-questions#will-androbd-support-additional-non-obd-sensor-data
Good luck
