### ISSUE TITLE
Service 0x0A not supported

### ISSUE THREAD

**Issue by monikamishra-54** [fr3ts0n/AndrOBD#229]
# Describe the bug

OBD protocol error

## Expected behavior

Torque app showing P0532 error but in AndrOBD app shows Service 0x0A not supported

## AndrOBD Debug log files
[AndrOBD.log.3.txt](https://github.com/fr3ts0n/AndrOBD/files/10323366/AndrOBD.log.3.txt)

## Additional context

Screenshot of Torque app
![1672383071493](https://user-images.githubusercontent.com/58734760/210043154-83cb923d-4ea9-4db0-bfe7-9809c9cb6405.jpg)

**Comment by fr3ts0n** [comment]
Pls attach Log Files with protokol (FINE) information. 
The only thing I can see in the file is that you switched between modes and Mode 10 ist rejected...

**Comment by monikamishra-54** [comment]
[AndrOBD.log.0 (1).txt](https://github.com/fr3ts0n/AndrOBD/files/10323560/AndrOBD.log.0.1.txt)

**Comment by monikamishra-54** [comment]
Hello sir ,
we did not clear DFC in whole process.
also is your code does not support DTC services ?

**Comment by fr3ts0n** [comment]
In above log file you can see that the ECU rejects a request to service 0x0A with NFC 0x11 (Not supported)
The log does NOT contain any request to other DTC services

AndrOBD does support all three services specified by OBD concerning DTC reading (0x3, 0x7, 0xA) and one for clearing DTC's (0x4)

As mentioned above, the torque app may also read other, non OBD services, which AndrOBD does NOT.

**Comment by monikamishra-54** [comment]
AndrOBD does support all three services specified by OBD concerning DTC reading (0x3, 0x7, 0xA) and one for clearing DTC's (0x4)
Said above it should support 0xA service but after clearing fault code its still showing obd protocol error
![1672407861697](https://user-images.githubusercontent.com/58734760/210076783-4a9ecafa-ad28-45e5-bef5-e78d126c4cb3.jpg)

**Comment by fr3ts0n** [comment]
This is not the app lacking support.
This is YOUR VEHICLE reporting the lack of support!
