### ISSUE TITLE
Ability to write to ECU?

### ISSUE THREAD

**Issue by Geremia** [fr3ts0n/AndrOBD#247]
AndrOBD allows resetting the ECU after a repair, but aren't there other ECU-writing functions AndrOBD could do (change/reset idle RPM, update VIN, etc.)?

<sup>cf. [this SoftwareRecs.StackExchange question](https://softwarerecs.stackexchange.com/q/45363/24575)</sup>

**Comment by fr3ts0n** [comment]
No, OBD protocol does not allow any changes to the vehicle. The time of last clearing of faults is also registered and reported by the protocol.
All changing and writing operations are done with OEM specific protocols.

**Comment by Geremia** [comment]
@fr3ts0n Oh, so there's no standard, open protocol for writing.
🙏s.
