### ISSUE TITLE
Permission denied error when loading customizations

### ISSUE THREAD

**Issue by hugglesfox** [fr3ts0n/AndrOBD#253]
Hi, thanks for the amazing app! 
I'm trying to use the protocol customization csv files to add some vehicle specific can PIDS however I'm encountering the following. 

# Describe the bug

When trying to load protocol customizations (as described in [AndrOBD_Documentation.odt](https://github.com/fr3ts0n/AndrOBD/blob/master/manual/AndrOBD_Documentation.odt)), an error regarding document read permissions pops up.

![Screenshot_20240111-223730_Trebuchet](https://github.com/fr3ts0n/AndrOBD/assets/25257393/64d519ac-4fd7-4764-a535-e1accdc0a186)

Possibly related to scoped storage being required in android 11. 
https://developer.android.com/about/versions/11/privacy/storage#scoped-storage

## To Reproduce

1. Go to Settings->Development options
2. Select CSV files for Data Conversions and Data Items under protocol customizations
3. Restart AndrOBD

## Expected behavior

The protocol customization files are loaded and the custom PIDS are available.

## AndrOBD Debug log files

[AndrOBD.log.0.txt](https://github.com/fr3ts0n/AndrOBD/files/13902618/AndrOBD.log.0.txt)

## Important details on your environment:

- Android OS version: 11
- AndrOBD version: 2.6.7
- OBD adapter type: N/A
- Connected vehicle make, type, year, engine size: N/A

Thanks!

**Comment by fr3ts0n** [comment]
Test version V2.6.9: https://t.me/AndrOBD_dev/256
