### ISSUE TITLE
You stopped adding new versions to the tags/releases section - no new F-Droid releases

### ISSUE THREAD

**Issue by ieffuie4** [fr3ts0n/AndrOBD#265]
I do not know if this is intended or not, but you stopped making new F-Droid releases by stopping adding the new versions to https://github.com/fr3ts0n/AndrOBD/tags 
The current version release of AndrOBD is V2.6.10: https://github.com/fr3ts0n/AndrOBD/commit/453e39d51ed8ce1222c9ab61e0b04fd54c1aa176
F-Droid is still on V2.6.7: https://f-droid.org/packages/com.fr3ts0n.ecu.gui.androbd/
Would be great to have the upcoming BLE supported version of AndrOBD on F-Droid: https://github.com/fr3ts0n/AndrOBD/issues/241#issuecomment-2211710301

**Comment by fr3ts0n** [comment]
Sorry for that. 
I thought that I have released V2.6.10 officially, but obviously I didn't.
Shame on me ...

Just released V2.6.12 to get all fixes and translations out officially
