### ISSUE TITLE
'com.github.mik3y:usb-serial-for-android:3.3.0' dispeared from jitpack.io

### ISSUE THREAD

**Issue by linsui** [fr3ts0n/AndrOBD#266]
# Describe the bug

'com.github.mik3y:usb-serial-for-android:3.3.0' dispeared from jitpack.io. Please update it to 3.3.1.

## AndrOBD Debug log files

Please attach AndrOBD debug log files.

AndrOBD stores log files in a subdirectory on your primary storage device. (com.fr3ts0n.ecu.gui.androbd/log/AndrOBD.log.*)

### Log detail level

The detail level of the logged debug information can be adjusted in the Settings > Development options > Logging level.

By default the detail level is set to INFO.
Preferred detail level for issue analysis is DEBUG. (Since V1.5.0 this level is called FINE)

## Important details on your environment:

- Android OS version:
- AndrOBD version:
- OBD adapter type:
- Connected vehicle make, type, year, engine size:

**Comment by fr3ts0n** [comment]
Thx for reporting.
Updated to latest release V3.8
