### ISSUE TITLE
AndrOBD intent conflicts with contacts

### ISSUE THREAD

**Issue by eshattow** [fr3ts0n/AndrOBD#3]
When using the contacts viewer on Android, I select a contact and am asked whether I want to open it using Contacts or using AndrOBD.  Why is that?

**Comment by danielmmmm** [comment]
It does not only want to open contacts but other files/intents as well. I think LocationMapViewer had a simmilar issue and (I think) it is not very difficult to fix:
https://github.com/k3b/LocationMapViewer/issues/2

**Comment by fr3ts0n** [comment]
I just remove the VIEW intent, since it only works with a limited number of file managers.
It is still possible to load .obd files from inside the app

**Comment by danielmmmm** [comment]
Thanks a lot :-)
