### ISSUE TITLE
ABS Speed Sensors

### ISSUE THREAD

**Issue by treestryder** [fr3ts0n/AndrOBD#37]
Is there a way to read ABS Speed Sensor information? If not, could such be added?

**Comment by fr3ts0n** [comment]
Hello @treestryder ,
Sorry, but ABS speed sensor is not supported via the OBD protocol.

**Comment by treestryder** [comment]
That is unfortunate.

Thank you for answering and for your handy app.

**Comment by treestryder** [comment]
Lemme guess. Tire Pressure is also not supported via the OBD protocol?
