### ISSUE TITLE
App crash when trying to load a non .obd file

### ISSUE THREAD

**Issue by Vince-King** [fr3ts0n/AndrOBD#43]
Hi again :)

Yes, I must be one of the stupid people... I tried to load a log file as the main .obd file.

I was surprised to find that the app tried to accept the .log file though. Not really surprised that the app crashed because of it.

Any chance you can add a sanity check on the file type, to stop stupid people like me crashing out. Maybe a toast, "Must be a .obd file" ?

Thanks

Vince

**Comment by fr3ts0n** [comment]
Thanks for the report.

I'll add a sanity check to fix that for next release.
