### ISSUE TITLE
Modernize the app's icon 

### ISSUE THREAD

**Issue by Ventto** [fr3ts0n/AndrOBD#47]
Hi @fr3ts0n, 
Thanks a lot for your work.

If by chance, you are interested in modernizing the app's icon, I offer my skills in flat design.

**Comment by fr3ts0n** [comment]
Hi @ventto,

Thanks for the offer. 
Yes I really would appreciate some help, since graphics design obviously is not my strength.

**Comment by fr3ts0n** [comment]
Do you already have any idea/draft for a new icon?
V2.0 release would be a good point to introduce a new icon :smile: 
Thx

**Comment by Ventto** [comment]
Hi @fr3ts0n,
I just read your reply.  I'll share it on this post soon.
