### ISSUE TITLE
Propose new logo

### ISSUE THREAD

**Issue by anaufalm** [fr3ts0n/AndrOBD#50]
Hi, I've seen your app and I think it's a lot of benefits, especially for the drivers. And here I would like to propose new logo for your app to have a good brand and become more interesting.

If you are interested and allowed me, I will make it for you, because I have an idea for this. ;)

**Comment by fr3ts0n** [comment]
Hi @anaufalm ,

I already do have another offer to get a new logo created. ( #47 by @Ventto ) 
I would appreciate to get another suggestion for the artwork, but it may end up in something like a challenge between all of you.

I would like to suggest an election of the best logo/artwork when all drafts are available.

Would that be ok with you?

**Comment by anaufalm** [comment]
Yeah sure, I have a draft but not ready yet. I'll present asap, soon maybe :)

**Comment by fr3ts0n** [comment]
Hi @anaufalm ,
Thanks you for these design drafts. 
This is beautiful artwork.

My personal favorite currently is:
![image](https://user-images.githubusercontent.com/2822578/38575424-ae3456cc-3cfb-11e8-84b7-662a6b212964.png)

Do you see any chance to change the 2-lined version to read "androbd" rather than "andro obd"?
I understand that this would be much better for icons / etc. 

Thanks

**Comment by anaufalm** [comment]
Yeah sure, go to fix it. So, you pick the purple?

**Comment by anaufalm** [comment]
What kind size you want @fr3ts0n?

**Comment by fr3ts0n** [comment]
Hi @anaufalm ,

Looks very nice to me. I also like the ones with the a and o being the wheels of the car ...

Do you already know which CC licence model you want to put this on?

This is also the last chance for @Ventto to challenge your design ...

**Comment by anaufalm** [comment]
This is [yours](), all of them. Color, size, vector files, svg for scalable size, and pdf files. Also your icon, because this app is for android, so I make a size base on [Icon Design Guidelines](https://developer.android.com/guide/practices/ui_guidelines/icon_design.html), I created all. You can see in the folder. :)

**Comment by fr3ts0n** [comment]
Thank you very much, CC BY is fine with me. You will definitely get the credits for this ...
I'll just leave @Ventto another week to challenge your design.
Is that ok with you?

**Comment by anaufalm** [comment]
Yeah, its ok. Its up to you, how good what you think. I will be happy if my work is worn. :D

**Comment by anaufalm** [comment]
Hi @fr3ts0n, how is it going? It's past two weeks. I seen @Venttoo didn't do it. 
What about my logo?

**Comment by fr3ts0n** [comment]
Hi @anaufalm ,
Sorry for my late  response. I have been quite busy with my garden so I haven't been much online lately.

Yes, since @Ventto did not react on the possible challenge it will definitely be your design.
Please could you provide the corresponding files for icon, logo, svg for integration? 
(In a previous post you mentioned a folder which I did not find)

Thank you very much

**Comment by anaufalm** [comment]
Sorry forget update the link, I will do it soon. Im on the way.

**Comment by anaufalm** [comment]
Hi @fr3ts0n sorry Im late, [this](https://drive.google.com/open?id=1XP6E1lz6cFLE9Ynln2YchXlYu87lNqkL) is yours.

**Comment by av2k** [comment]
@anaufalm @fr3ts0n  Thank you very much! The design looks really good. I'm not even a AndrOBD / ODB2 user but saw this ticket and it displays exactly the spirit why the open source scene is so good. 👍 :)

**Comment by anaufalm** [comment]
@av2k Well, at first I found this app in F-Droid, and feel there is less with the logo. And that's the reason why I'm here. :D

**Comment by fr3ts0n** [comment]
Integrated and released with V2.0.3 :smiley:

Your credits are linked to your GitHub page, I hope this is OK for you ...

![screenshot_1527760407](https://user-images.githubusercontent.com/2822578/40775834-5676165a-64c9-11e8-8922-4588f5e52772.png)

Thank you again for your contribution.

**Comment by anaufalm** [comment]
Yeaay, its enough. ;)

**Comment by anaufalm** [comment]
Bonus for you

![androbd-mockup4](https://user-images.githubusercontent.com/35919168/40831906-6bb12a28-65b4-11e8-9046-82c5cdb26792.png)

![androbd-mockup2](https://user-images.githubusercontent.com/35919168/40831981-94e7d66c-65b4-11e8-99eb-2caffa8ddf56.png)

**Comment by fr3ts0n** [comment]
Hey, this is great for the start page ...
Thanks again

**Comment by anaufalm** [comment]
You are welcome
