### ISSUE TITLE
Failed to connect to a 2017 VW Jetta

### ISSUE THREAD

**Issue by oroce** [fr3ts0n/AndrOBD#52]
Hey, I tried to connect to a 2017 (february) VW Jetta. After I select the bluetooth adapter the label goes online and immediately goes back to offline. the notification on the bottom says: `Device connection was lost.`

Torque lite and premium works without any problem.

In Torque I was able to connect to the car with turned off timing. As it can be seen in the log I tried with all the timing options.

[AndrOBD.log.1vwjetta.txt](https://github.com/fr3ts0n/AndrOBD/files/1868535/AndrOBD.log.1vwjetta.txt)

Android:
![screenshot_20180402-180151](https://user-images.githubusercontent.com/462848/38203672-43525414-36a0-11e8-85d6-d29b0dc11ec7.jpg)

App version:
![screenshot_20180402-180230](https://user-images.githubusercontent.com/462848/38203668-3f7fd406-36a0-11e8-85c2-e99b5b1fa57b.jpg)

**Comment by Fraifrai** [comment]
Hi,
same problem with SEAT IBIZA 2013

**Comment by fr3ts0n** [comment]
Based on the log file of the VW Jetta it seems that your adaptor breaks the Bluetooth connection on the ATZ (reset) command. I have seen this happen with several adaptors already.

I would suggest to disable the ATZ command in the AndrOBD settings:
Settings -> Development options -> Disabled ELM commands -> check "ATZ"

This should eliminate the device reset and allow the bluetooth connection to stay alive.

Please let me know the results

**Comment by Fraifrai** [comment]
This trick worked for my SEAT IBIZA ST FR 1.2 TSI 105

thanks

**Comment by oroce** [comment]
@fr3ts0n thanks. Unfortunately, I don't have access to the Jetta right now, but I guess this has nothing to do with the car but rather with the adapter, right? So I should see the same issue with other cars and I guess that same trick would solve this problem.

**Comment by Fraifrai** [comment]
@oroce : regarding my answer you should try. As it worked with my SEAT it shall work for any recent VW group car

**Comment by fr3ts0n** [comment]
@oroce: Yes you are right. 
It is an issue of the combination of adapter- and mobile device. 
You will face the same situation on other cars as well, but the setting of **ATZ** command disabled should fix that situation for all vehicles.

**Comment by Fraifrai** [comment]
@fr3ts0n it seems to be a recurrent problem. What about disabling this command in the default settings ?

**Comment by fr3ts0n** [comment]
@Fraifrai This setting stays consistent with your installation for all following app usage.
This is only reset to default values if you de- and re-install the app, so I don't really see the necessity of changing the workaround into the default settings. 
The ATZ command is handled by most adapters without any problems in BT communication ...

**Comment by Fraifrai** [comment]
maybe a comment about it in the settings should avoid such issues opening.

**Comment by fr3ts0n** [comment]
I've added this subject to the [FAQ Wiki page](https://github.com/fr3ts0n/AndrOBD/wiki/Frequently-asked-questions)

**Comment by oroce** [comment]
I just wanted to confirm that disabling ATZ command resolved the issue for me, too. thanks @fr3ts0n
