### ISSUE TITLE
Can the collected data also include GPS?

### ISSUE THREAD

**Issue by itamar-otonomo** [fr3ts0n/AndrOBD#54]
That way I would be able to correlate OBD data with location and speed?

**Comment by fr3ts0n** [comment]
That sounds like a good AndrOBD extension plugin project ...

see: https://github.com/fr3ts0n/AndrOBD-Plugin

Anybody interested to create this?

**Comment by jgpATs2w** [comment]
Hi, I was planning to include the functionality to send data to a remote server, and already have an android project with gps data collection, so I would do it!
I've made a question about the creation of a new plugin: https://github.com/fr3ts0n/AndrOBD-Plugin/issues/3

**Comment by abalage** [comment]
I would love to see this feature. I can offer my help for testing.

Currently I use 'Carscanner' to have CSV export and Trackbook (https://f-droid.org/en/packages/org.y20k.trackbook/) to have GPS data and merge them together with a script. It is uncomfortable and prone to errors (timing mismatch).

**Comment by fr3ts0n** [comment]
Test versions are available now for your tests on [AndrOBD dev channel](https://t.me/AndrOBD_dev)
- AndrOBD V2.1.0 (for support of handling plugin provided data in data list)
- GpsProvider plugin V1.0.0

**Comment by fr3ts0n** [comment]
Support added with V2.1.0 + GpsProvider V1.0.0

**Comment by abalage** [comment]
>
> Test versions are available now for your tests on [AndrOBD dev channel](https://t.me/AndrOBD_dev)
> 
Unfortunately meanwhile I have already purchased another tool for the same purpose.
However I really appreciate the effort you did put into this feature.
