### ISSUE TITLE
Built-in terminal

### ISSUE THREAD

**Issue by toxub23** [fr3ts0n/AndrOBD#56]
You could add a built-in terminal to send commands via the OBD interface. You could also add a database of sample commands that you can send.

**Comment by fr3ts0n** [comment]
Thanks for your suggestion.

I think the advantage of AndrOBD is to operate the adapter and visualize the vehicle readings without having to care about the  ELM commands or OBD specifications. 

For experimenting with the ELM command set using terminal mode there are several other, better apps out there. 

I also have one of these installed for experimenting with some special sequences via mobile device. (https://play.google.com/store/apps/details?id=com.app.elm327terminal&hl=en)
