### ISSUE TITLE
Add a scan function for an addressrange

### ISSUE THREAD

**Issue by fr3ts0n** [fr3ts0n/AndrOBD#6]
Enhancement: Add a scan function for an addressrange

I think I need some more details on that one.
Are you asking for scanning a range of ECU addresses? If so, we are probably talking about UDS protocol using vendor specific PID maps and conversions rather than OBD, which is standardized.
I know that it is possible with a ELM, but I'm just not there yet.

**Comment by pfuender** [comment]
Well to be honest, I don't know much about the whole obd/udp/pid protocol stuff behind, but I was running [Torque](https://play.google.com/store/apps/details?id=org.prowl.torquescan), which has such a functionality. I guess once *you* have a look at it, you know what I'm talking about.

Thanks

**Comment by fr3ts0n** [comment]
Allow ECU selection by address if more than one ECU respond to OBD requests.
implemented with V1.3.3
