### ISSUE TITLE
Source strings in Weblate are in Portuguese

### ISSUE THREAD

**Issue by yarons** [fr3ts0n/AndrOBD#68]
My Portuguese knowledge is pretty poor so I can't understand most of it, can you please revert it and place the translations in the right place?

**Comment by fr3ts0n** [comment]
Thanks for reporting this.
Someone seems to have modified the english strings on weblate. However, the changes haven't been pushed to GitHub sources yet, so I dodn't notice yet.

I have reverted the weblate changes again, so english reference text should be available again. :+1:

**Comment by yarons** [comment]
Thanks :)
