### ISSUE TITLE
ECU not detected in case of wifi 

### ISSUE THREAD

**Issue by shikha805** [fr3ts0n/AndrOBD#70]
There is problem in ecu detection in case of wifi. Its working perfectly on bluetooth. Sometimes it detects ecu but most of time, it shows "ecu detecting" ,but it does not connect. It seems ecu is detected on api level upto  27.But there is problem in api 28.Please resolve this issue.

**Comment by fr3ts0n** [comment]
Thanks for your report.

Pls can you attach some log files to analyze what happens on your device.
see https://github.com/fr3ts0n/AndrOBD/wiki/Reporting-improvements---issues
Thx
