### ISSUE TITLE
Add support for tasker

### ISSUE THREAD

**Issue by krzyk** [fr3ts0n/AndrOBD#73]
It would be good to be able to:
1. Connect to OBD
2. Start collecting data
3. Publish all data using MQTT
4. Disconnect from OBD

Using Android Intents, and publish them on wiki so one can call them from tasker.

My use case is to have publish all OBD data collected published when my phone connects to my car Bluetooth (send intent to connect to OBD/start collecting data/publish data to MQTT), and stop it when my phone disconnects from bluetooth.

Example of great tasker integration is GPSLogger project, see their FAQ regarding Tasker here: https://gpslogger.app/#controllinggpslogger

**Comment by gabriellluz** [comment]
I second that.

Tasker misses some solution for OBD. We can automate anything but we can't acces OBD data. I really think that would be the first app of this kind with Tasker support.

**Comment by fr3ts0n** [comment]
Sorry for not responding so long.
I am currently working on another project, so I haven't looked into the details yet.

Couldn't this be done by the AndrOBDMqttPlugin just by a automated start of AndrOBD (by Tasker) on BT connect?

All the rest could be done by the AndrOBD startup settings.

**Comment by fr3ts0n** [comment]
The only thing to be automated for your scenario is the automated start/stop of AndrOBD on BT connect/disconnect.

All internal settings of AndrOBD startup behaviour can be set in AndrOBD preferences.
(see: https://github.com/fr3ts0n/AndrOBD/wiki/Automation-on-startup)

**Comment by wunter8** [comment]
I just tried it again today. I have all the checkboxes checked under "common settings" > "use last settings", but when I open the app, nothing happens until I click the "connect"/plug-shaped icon. Is that how it's supposed to be?

**Comment by fr3ts0n** [comment]
You are correct. The app currently requires a manual "connect" action. 
I'll fix that so it will auto-connect when started and auto-connect is preferred

**Comment by wunter8** [comment]
That'd be awesome! Thanks!

**Comment by wunter8** [comment]
That was quick. Thanks! I'll watch for the update through F-Droid

**Comment by fr3ts0n** [comment]
Test version is available here:
https://t.me/AndrOBD_dev/252

F-Droid update will be triggered soon
