### ISSUE TITLE
Orientation bug in Gauges view 

### ISSUE THREAD

**Issue by kamilr** [fr3ts0n/AndrOBD#88]
**Describe the bug**
When You choose two of data sources to show in Gauges view and after correct eg. vertical view You rotate Your device to eg. horizontal view: the gauges are still one above another, not next to themselves. 
**To Reproduce**
1. Activate dynamically oriented screen in Your OS, do not change Your phone screen orientation till the step 7 and run the application.
2. Successfully connect to OBD adapter
3. Click on (3rd) icon of dropdown menu related with OBD
4. Choose "OBD Data"
5. Choose two factors to be used in gauges view (long click in version 2.1.1)
6. Click on Gauges view icon and see correct view of gauges.
7. Now change orientation of Your device from previous to perpendicular.
8. The bug is shown as a scroll-able view with empty areas in the view.

**Expected behavior**
New rotated gauges view is reloaded to fit new app orientation.

**Important details on your environment:**
- Android OS version : LOS 16
- AndrOBD version : 2.1.1
- OBD adapter type : unnecessary 
- Connected vehicle make, type, year, engine size : unnecessary 

**Additional context**
If it is not the bug-behaviour: Sorry for dissipating.

**Comment by fr3ts0n** [comment]
Thanks for your report

Yes, I can verify that.
Will be fixed soon
