### ISSUE TITLE
Check background picture is distracting

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#95]
In the Obd Data menu, the Check Engine wallpaper/background is distracing so the text is not as visible.

I recommend that the icon is moved to the top bar, and the background is changed. 

![](https://i.imgur.com/oPf4Kr0.png)

![](https://i.imgur.com/AbBCkGr.png)

**Comment by fr3ts0n** [comment]
The big check engine light is designed that way.
It shall be easily visible in case OBD protocol indicates the check engine light to be ON.
- In full screen mode
- With status bar disabled

**Comment by aha999** [comment]
Maybe you could use a first row for displaying a text: **MIL Status: ON/OFF** and a small version of this logo that indicates it's on (bright yellow) or off (dark), like in a car. This way it would look much better. 
i believe not a lot of people would assume that the background could mean that the MIL is actually on, because if it is, it should be displayed like other info.

**Comment by blommetjie** [comment]
Nothing coudent do noting to mil

**Comment by fr3ts0n** [comment]
I really think it is fine to display an active MIL like it currently is. 
If you regularly test and measure your vehicle, it does not affect you at all, but if your MIL is active it shall be distracting somehow, since it is supposed to warn you of a problem with your car.

**Comment by aha999** [comment]
yes, but the point is that MIL is massive and in the background so it is distracting. On the top it says "MIL status ON" anyways... maybe you can add a small MIL logo to that line... And the background would look cleaner
