### ISSUE TITLE
Long pressing the DFC doesn't open a website / info

### ISSUE THREAD

**Issue by aha999** [fr3ts0n/AndrOBD#97]
When long pressing a DFC fault code, it doesn't open anthying like details, but throws an error. I think it should open the default web browser for example / trouble code lookup

![](https://i.imgur.com/9CMSAAu.png)

When long pressing a fault code:

![](https://i.imgur.com/So2owP5.png)

**Comment by fr3ts0n** [comment]
What kind of browser do you have installed on your device?
This is a standard Android web search request which triggers the browser to open a search for "OBD <DFC#>"
I haven't heard of any other reports of this not working ...

**Comment by aha999** [comment]
Maybe it's indeed a problem on my side because i've had this problem before recently on another program...

**Comment by aha999** [comment]
The problem was on my side, the browser had a bug that got fixed. Closing the issue.
